import { NextRequest } from "next/server";
import { json, error, requireRole } from "@/lib/api-helpers";
import { prisma } from "@/lib/prisma";

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await requireRole("SUPER_ADMIN");
  if (!session) return error("Forbidden", 403);

  const { id } = await params;
  const fine = await prisma.fine.findUnique({ where: { id } });
  if (!fine) return error("Fine not found", 404);

  await prisma.fine.delete({ where: { id } });

  // Absent fines are auto-regenerated by payroll.service.ts on every page
  // load (it walks ABSENT attendance and ensures each has a matching fine
  // record). Deleting just the fine doesn't stick — the underlying ABSENT
  // attendance is the source of truth. To make manual deletions persist,
  // flip the corresponding attendance day from ABSENT to ON_LEAVE so the
  // regeneration loop skips it. Treats CEO deletion as "absence excused."
  if (fine.type === "ABSENT_WITHOUT_LEAVE") {
    await prisma.attendance.updateMany({
      where: { userId: fine.userId, date: fine.date, status: "ABSENT" },
      data: { status: "ON_LEAVE", notes: "Excused by CEO (fine removed)" },
    });
  }

  // Sync payroll record after fine removal
  try {
    const { syncPayrollRecord } = await import("@/lib/services/payroll-sync.service");
    await syncPayrollRecord(fine.userId, fine.month, fine.year);
  } catch {}

  return json({ success: true });
}
